### ISSUE TITLE
wire:model value is not show

### ISSUE THREAD

**Issue by teguhoktian** [dasundev/livewire-quill-text-editor#1]
`<livewire:quill-text-editor wire:model.live="body" theme="snow" />`

not show body content

**Comment by dasundev** [comment]
@teguhoktian I have tried the snow theme, it is working!

Make sure you have this line in your blade layout.
```html
<!-- Include Bubble Theme -->
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
```

**Comment by teguhoktian** [comment]
I try to publish quill-text-editor component, and did something like this and work. 

`<quill-text-editor> {!! body!!}</quill-text-editor>`
