### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by ifkas** [dasundev/livewire-quill-text-editor#10]
I followed the exact same steps as on the Readme from the repo, but all I got on the screen is this: **@script @endscript**
Here is a screenshot:
![image](https://github.com/dasundev/livewire-quill-text-editor/assets/987112/2e4c47f5-1d8e-4943-a794-b6745005ab63)

What am I missing? Thanks.

**Comment by dasundev** [comment]
What's your Laravel version?

**Comment by dasundev** [comment]
Closing issue due to no response.
