### ISSUE TITLE
Cant use 2 editors in the same page

### ISSUE THREAD

**Issue by hipoagencia** [dasundev/livewire-quill-text-editor#6]
Hi!
Its impossivel to use 2 components in the same page.
When you get the values, they only bring the first texteditor value for both.

**Comment by dasundev** [comment]
Can you make a PR?

**Comment by hipoagencia** [comment]
Sorry.. i don't know how to do this? :(

**Comment by muhammedjafer** [comment]
@dasundev , @hipoagencia , i had the same issue i fixed it here is the code below, but first you need to publish the blade component and inside the blade component in the below put this code instead, 

`   quill.on('text-change', function () {
        let value = document.querySelector('#' + @js($quillId)).firstChild.innerHTML;
        @this.set('value', value);
    });`

**Comment by dasundev** [comment]
@muhammedjafer Can you make a PR?

**Comment by muhammedjafer** [comment]
> Can you make a PR?

i fixed it here is the code 
![Screenshot 2024-04-18 162536](https://github.com/dasundev/livewire-quill-text-editor/assets/56185049/6e611107-825d-434b-9440-1218a04c1d30)

**Comment by muhammedjafer** [comment]
> @muhammedjafer Can you make a PR?

how can i do that ???

**Comment by muhammedjafer** [comment]
> @muhammedjafer Can you make a PR?

i can not make a pull request i don't have the permissoins

**Comment by muhammedjafer** [comment]
> @muhammedjafer Can you make a PR?

make me a contributor so then i can push the code to github, i don't have the permissions i can not push the fix to your github repository

**Comment by muhammedjafer** [comment]
> @muhammedjafer Can you make a PR?

??

**Comment by hipoagencia** [comment]
> > You must first fork the repository.
> > Please follow this guide: https://www.dataschool.io/how-to-contribute-on-github/
> 
> i forked the repo and made a new pull request, now what should i do next?

Maybe.. relax a little bit? :P

**Comment by dasundev** [comment]
> > You must first fork the repository.
> > Please follow this guide: https://www.dataschool.io/how-to-contribute-on-github/
> 
> i forked the repo and made a new pull request, now what should i do next?

I can't see any PR yet.

**Comment by muhammedjafer** [comment]
> > > You must first fork the repository.
> > > Please follow this guide: https://www.dataschool.io/how-to-contribute-on-github/
> > 
> > 
> > i forked the repo and made a new pull request, now what should i do next?
> 
> I can't see any PR yet.

i made it, look at it now

**Comment by muhammedjafer** [comment]
> > > You must first fork the repository.
> > > Please follow this guide: https://www.dataschool.io/how-to-contribute-on-github/
> > 
> > 
> > i forked the repo and made a new pull request, now what should i do next?
> 
> I can't see any PR yet.

sorry it took me awhile to make the rp, it was my first time forking a repo from github

**Comment by dasundev** [comment]
That's totally fine. You are doing well. I will review your PR.

**Comment by muhammedjafer** [comment]
> That's totally fine. You are doing well. I will review your PR.

wanted to say that i used four text editor at the same page for update and create using ur package, and i preload the data of the editors on update, all in one component, thanks for ur awesome package, wish u the best, and i am here for any help u want!

**Comment by dasundev** [comment]
I made a small change to enhance the code's quality. Thanks for your support! ❤️
